// This file was autogenerated by /Users/Orga/Sites/Dropbox/Program/javascript/GoogleCodePrettify-WorkSpace/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../google-code-prettify/js/lang-clj.js', ['prettify.clojure'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-css.js', ['prettify.css'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-go.js', ['prettify.go'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-hs.js', ['prettify.haskell'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-lisp.js', ['prettify.lisp'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-lua.js', ['prettify.lua'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-ml.js', ['prettify.ml'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-n.js', ['prettify.nemerle'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-proto.js', ['prettify.protocolBuffers'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-scala.js', ['prettify.scala'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-sql.js', ['prettify.sql'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-tex.js', ['prettify.tex'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-vb.js', ['prettify.visualBasic'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-vhdl.js', ['prettify.vhdl'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-wiki.js', ['prettify.wiki'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-xq.js', ['prettify.xquery'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/lang-yaml.js', ['prettify.yaml'], ['prettify']);
goog.addDependency('../../../google-code-prettify/js/prettify.js', ['prettify'], []);
